name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Jenkins Job
      env:
        JENKINS_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        JENKINS_USER: sarawutadmin
        JENKINS_URL: http://20.2.250.65:8080
        JOB_NAME: dotnetcicd
        BUILD_TOKEN: ghdsajxppweipe889932pa3sax
      run: |
        # Get Jenkins crumb for CSRF protection
        CRUMB_RESPONSE=$(curl -s -u "${JENKINS_USER}:${JENKINS_TOKEN}" \
                         "${JENKINS_URL}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
        
        if [[ $CRUMB_RESPONSE == *":"* ]]; then
          CRUMB=$CRUMB_RESPONSE
          echo "Crumb obtained successfully"
        else
          echo "Failed to obtain crumb: $CRUMB_RESPONSE"
          exit 1
        fi
        
        # Trigger Jenkins job
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
                   -X POST "${JENKINS_URL}/job/${JOB_NAME}/build?token=${BUILD_TOKEN}" \
                   -u "${JENKINS_USER}:${JENKINS_TOKEN}" \
                   -H "$CRUMB")
        
        if [ "$RESPONSE" = "201" ]; then
          echo "Jenkins job triggered successfully"
        else
          echo "Failed to trigger Jenkins job. HTTP response code: $RESPONSE"
          # Add more debugging information
          curl -v -X POST "${JENKINS_URL}/job/${JOB_NAME}/build?token=${BUILD_TOKEN}" \
               -u "${JENKINS_USER}:${JENKINS_TOKEN}" \
               -H "$CRUMB"
          exit 1
        fi

    - name: Check Jenkins Accessibility
      env:
        JENKINS_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        JENKINS_USER: sarawutadmin
        JENKINS_URL: http://20.2.250.65:8080
      run: |
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
                   -u "${JENKINS_USER}:${JENKINS_TOKEN}" \
                   "${JENKINS_URL}")
        if [ "$RESPONSE" = "200" ]; then
          echo "Jenkins is accessible"
        else
          echo "Failed to access Jenkins. HTTP response code: $RESPONSE"
          exit 1
        fi
