name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Jenkins Job
      env:
        JENKINS_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        JENKINS_USER: sarawutadmin
        JENKINS_URL: http://20.2.250.65:8080
        JOB_NAME: dotnetcicd
        BUILD_TOKEN: ghdsajxppweipe889932pa3sax
        PORT: 5000
      run: |
        # Function to check if Jenkins is accessible
        check_jenkins_accessibility() {
          local response=$(curl -s -o /dev/null -w "%{http_code}" -u "${JENKINS_USER}:${JENKINS_TOKEN}" "${JENKINS_URL}")
          if [ "$response" = "200" ]; then
            echo "Jenkins is accessible"
            return 0
          else
            echo "Failed to access Jenkins. HTTP response code: $response"
            return 1
          fi
        }

        # Check Jenkins accessibility first
        if ! check_jenkins_accessibility; then
          echo "Jenkins is not accessible. Exiting."
          exit 1
        fi

        # Get Jenkins crumb for CSRF protection
        echo "Getting CSRF crumb..."
        CRUMB_RESPONSE=$(curl -s -u "${JENKINS_USER}:${JENKINS_TOKEN}" \
                         "${JENKINS_URL}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
        
        if [[ $CRUMB_RESPONSE == *":"* ]]; then
          CRUMB=$CRUMB_RESPONSE
          echo "Crumb obtained successfully: $CRUMB"
        else
          echo "Failed to obtain crumb: $CRUMB_RESPONSE"
          exit 1
        fi

        # Trigger Jenkins job with parameters
        echo "Triggering Jenkins job..."
        RESPONSE=$(curl -s -o response.txt -w "%{http_code}" \
                   -X POST "${JENKINS_URL}/job/${JOB_NAME}/buildWithParameters?PORT=${PORT}" \
                   -u "${JENKINS_USER}:${JENKINS_TOKEN}" \
                   -H "$CRUMB" \
                   -H "Content-Type: application/x-www-form-urlencoded" \
                   --data-urlencode "token=${BUILD_TOKEN}")
        
        echo "Response code: $RESPONSE"
        cat response.txt
        
        if [ "$RESPONSE" = "201" ] || [ "$RESPONSE" = "302" ]; then
          echo "Jenkins job triggered successfully"
        else
          echo "Failed to trigger Jenkins job. HTTP response code: $RESPONSE"
          exit 1
        fi

    - name: Check Jenkins Accessibility
      env:
        JENKINS_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        JENKINS_USER: sarawutadmin
        JENKINS_URL: http://20.2.250.65:8080
      run: |
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
                   -u "${JENKINS_USER}:${JENKINS_TOKEN}" \
                   "${JENKINS_URL}")
        if [ "$RESPONSE" = "200" ]; then
          echo "Jenkins is accessible"
        else
          echo "Failed to access Jenkins. HTTP response code: $RESPONSE"
          exit 1
        fi
